# ===== config.yaml =====
# MuseQuill V3 Pipeline Configuration
# Complete configuration for the adversarial book generation system

# Core pipeline settings
pipeline:
  max_generation_attempts: 5
  max_revision_cycles: 3
  orchestration_strategy: "balanced"  # quality_first, speed_optimized, balanced, experimental
  parallel_variant_evaluation: true
  enable_market_intelligence_refresh: true
  market_refresh_interval_hours: 24
  component_health_check_interval: 300
  enable_adaptive_orchestration: true
  pipeline_timeout_minutes: 60
  enable_comprehensive_logging: true
  fallback_on_component_failure: true

# Research integration settings
researcher:
  tavily_api_key: "${TAVILY_API_KEY}"  # Set as environment variable
  max_concurrent_requests: 3
  enable_caching: true
  cache_ttl_hours: 12
  quality_threshold: 0.7
  
  # Automatic research trigger conditions
  auto_trigger_conditions:
    market_data_age_hours: 6
    plot_inconsistency_threshold: 0.8
    character_development_gaps: true
    trend_analysis_frequency: "daily"

# Component-specific configurations
components:
  chapter_generator:
    model_name: "claude-3-sonnet"
    temperature: 0.8
    max_tokens: 4000
    creativity_boost: true
    style_consistency_weight: 0.7
    
  plot_coherence_critic:
    strictness_level: "moderate"  # strict, moderate, lenient
    continuity_weight: 0.8
    logic_consistency_weight: 0.9
    character_consistency_weight: 0.8
    
  literary_quality_critic:
    style_analysis_depth: "comprehensive"  # basic, moderate, comprehensive
    originality_threshold: 0.6
    prose_quality_threshold: 0.7
    voice_authenticity_weight: 0.8
    
  reader_engagement_critic:
    target_audience: "general_adult"
    engagement_threshold: 0.75
    emotional_impact_weight: 0.8
    pacing_consistency_weight: 0.7
    
  quality_controller:
    quality_threshold: 0.75
    enable_detailed_feedback: true
    weighted_scoring: true
    revision_suggestion_detail: "comprehensive"
    
  market_intelligence_engine:
    update_frequency_hours: 24
    search_depth: "advanced"  # basic, advanced
    max_search_results: 15
    enable_competitive_analysis: true
    trend_confidence_threshold: 0.6
    genres_to_track: ["romance", "thriller", "fantasy", "literary", "mystery", "sci-fi"]

# Output configuration
output:
  base_directory: "./output"
  save_intermediate_results: true
  export_formats: ["json", "text", "epub"]
  chapter_backup_frequency: 5  # Save backup every N chapters
  
  # File naming patterns
  naming:
    story_directory: "{title}_{timestamp}"
    chapter_files: "chapter_{number:02d}_{title_slug}.txt"
    backup_files: "backup_{timestamp}.json"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_directory: "./logs"
  enable_activity_tracking: true
  enable_performance_metrics: true
  max_log_file_size_mb: 100
  log_rotation_count: 5
  
  # Specific logger levels
  loggers:
    "pipeline.orchestrator": "INFO"
    "pipeline.generator": "INFO"
    "pipeline.critic": "INFO"
    "pipeline.researcher": "DEBUG"
    "pipeline.quality": "INFO"
    "pipeline.activity": "INFO"

# Performance and resource settings
performance:
  max_concurrent_chapters: 2
  memory_limit_gb: 8
  enable_gpu_acceleration: false
  thread_pool_size: 4
  
  # Caching settings
  cache:
    enable_component_caching: true
    enable_research_caching: true
    enable_market_data_caching: true
    cache_cleanup_interval_hours: 24
    max_cache_size_gb: 2

# Development and debugging
development:
  enable_debug_mode: false
  save_debug_artifacts: false
  enable_component_profiling: false
  mock_external_apis: false  # For testing without API keys
  
  # Testing overrides
  testing:
    mock_tavily_responses: false
    use_dummy_models: false
    fast_mode: false  # Skip some quality checks for speed

---

# ===== example_story_config.json =====
{
  "title": "The Neural Network",
  "genre": "sci-fi",
  "subgenre": "cyberpunk",
  "target_audience": "adult",
  "target_length": "novella",
  "estimated_chapters": 12,
  
  "premise": "In 2035, a neuroscientist discovers that human consciousness can be digitally transferred, but the technology falls into the wrong hands, threatening the nature of human identity itself.",
  
  "main_character": {
    "name": "Dr. Maya Patel",
    "role": "protagonist",
    "background": "Computational neuroscientist at Stanford, former DARPA researcher",
    "motivation": "Protect her revolutionary consciousness transfer technology from corporate exploitation",
    "personality_traits": ["brilliant", "protective", "ethically-driven", "haunted by past mistakes"]
  },
  
  "supporting_characters": [
    {
      "name": "Alex Chen",
      "role": "ally",
      "background": "Ethical hacker and Maya's former student",
      "motivation": "Help Maya expose the corporate conspiracy"
    },
    {
      "name": "Victoria Sterling",
      "role": "antagonist", 
      "background": "CEO of Nexus Technologies, ruthless tech mogul",
      "motivation": "Commercialize consciousness transfer for profit and control"
    }
  ],
  
  "themes": [
    "consciousness and identity",
    "corporate power vs individual rights",
    "the cost of technological progress",
    "what makes us human"
  ],
  
  "tone": "cerebral suspense with emotional depth",
  "pacing": "measured build to intense climax",
  
  "setting": {
    "primary_location": "San Francisco Bay Area",
    "secondary_locations": ["underground hacker collectives", "corporate boardrooms", "neural research labs"],
    "time_period": "2035",
    "tech_level": "near-future with advanced neural interfaces"
  },
  
  "plot_structure": {
    "type": "three_act",
    "act_1_focus": "discovery and initial threat",
    "act_2_focus": "escalating conflict and personal stakes", 
    "act_3_focus": "final confrontation and resolution"
  },
  
  "market_requirements": {
    "trend_awareness": true,
    "competitive_positioning": "unique take on consciousness transfer trope",
    "reader_engagement_focus": "high",
    "commercial_viability": "strong"
  },
  
  "research_priorities": [
    "current neuroscience breakthroughs",
    "consciousness philosophy",
    "tech industry power dynamics",
    "cyberpunk reader preferences",
    "emerging sci-fi trends"
  ],
  
  "quality_targets": {
    "plot_coherence_minimum": 0.8,
    "literary_quality_minimum": 0.75,
    "reader_engagement_minimum": 0.8,
    "originality_target": 0.85
  }
}
